### ISSUE TITLE
AgentConfigWrapper change wrapped AgentConfig internal state

### ISSUE THREAD

**Issue by suszczyr** [Cognifide/CQ-Transport-Handler#1]
Line 41 in  package com.cognifide.cq.cogtransport.AgentConfigWrapper:

```
String[] headers = originalProperties.get(PROTOCOL_HTTP_HEADERS, DEFAULT_HTTP_HEADERS);
```

should be sth like:

```
String[] originalHeaders = originalProperties.get(PROTOCOL_HTTP_HEADERS, DEFAULT_HTTP_HEADERS);
String[] headers = Arrays.copyOf(originalHeaders, originalHeaders.length);
```

Issue appeared on AEM6 (SP2) but not on CQ5.4
Headers when accessed first time are as expected:
host:{domain}, CQ-Action:{action}, CQ-Handle:{path}
and changed to sth like:
host:{www.exampledomain.com}, CQ-Action:{action}, CQ-Handle:{path}
which remains in such state after that for any following access.

This means that placholder {domain} is replaced with first replication event only

**Comment by trekawek** [comment]
Thanks for catching this! I applied suggested fix.
